### PR TITLE
Fix bug associated adding an geojson source url

### LINKED ISSUE #199: Bug caused when external/referenced JSON sources are used in style for the MapActivity
If you declare a source like below:

```json
"external-geojson-source-name": {
      "type": "geojson",
      "data": "https://gist.githubusercontent.com/ekigamba/436f21630bc11a565231bde7c8fca963/raw/f229ccf7b01841eb1edd003f7871eb6610006cef/gistfile1.txt"
    },

```

The MapActivity throws such an error
```
11-21 17:07:18.094 5320-5320/io.ona.kujaku.sample E/MapActivity: org.json.JSONException: Value https://gist.githubusercontent.com/ekigamba/436f21630bc11a565231bde7c8fca963/raw/f229ccf7b01841eb1edd003f7871eb6610006cef/gistfile1.txt at data of type java.lang.String cannot be converted to JSONObject
        at org.json.JSON.typeMismatch(JSON.java:100)
        at org.json.JSONObject.getJSONObject(JSONObject.java:613)
        at io.ona.kujaku.activities.MapActivity.extractLayerData(MapActivity.java:267)
        at io.ona.kujaku.activities.MapActivity.initializeMapActivityAfterPermissionsSupplied(MapActivity.java:163)
        at io.ona.kujaku.activities.MapActivity.checkPermissions(MapActivity.java:433)
        at io.ona.kujaku.activities.MapActivity.onCreate(MapActivity.java:119)
        at android.app.Activity.performCreate(Activity.java:6948)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2924)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3042)
        at android.app.ActivityThread.-wrap14(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1639)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6780)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
```

### PR DESCRIPTION
**Pull request by ekigamba**
Fixes #199

### CODE REVIEW

File: library/src/main/java/io/ona/kujaku/activities/MapActivity.java [hunk 1]
```diff
@@ -312,8 +312,8 @@ private void dismissAllDialogs() {
                 if (sources.has(dataSourceName)) {
                     JSONObject jsonObject = sources.getJSONObject(dataSourceName);
                     if (jsonObject.has("data")) {
-                        JSONObject sourceDataJSONObject = jsonObject.getJSONObject("data");
-                        if (sourceDataJSONObject.has("features")) {
+                        JSONObject sourceDataJSONObject = jsonObject.optJSONObject("data");
+                        if (sourceDataJSONObject != null && sourceDataJSONObject.has("features")) {
```
Comment (vincent-karuri) [inline library/src/main/java/io/ona/kujaku/activities/MapActivity.java]: Consider defining "features" once as a constant.
