### PR TITLE
Fix recursive loop causing StackOverflow error, permission checks, tests, my location button size

### LINKED ISSUE #162: Add permissions check & location services check
This makes sure that everything works OK

- [x] GPS OR high accuracy is enabled
- [x] Make sure location is enabled at the specific moment
- [x] Make sure the app has location permissions

### LINKED ISSUE #188: Prompt the user to turn on GPS if not enabled when they touch the my location button and add point button
The GeoWidget needs to ask the user to turn on the GPS if it's not currently enabled when they touch the my location button and add point button. This should be a modal notification that pops up as is currently done in Google Maps.

Step1: View request
screenshot_20181108-180844
Step 2: Detailed view of which version of location services will be enabled.
screenshot_20181108-180910

### PR DESCRIPTION
**Pull request by ekigamba**
Supposed to fix the following issues:

- #164 
- #162 
- #165
- Make my location button bigger

Fixes #162 
Fixes #188

### CODE REVIEW

File: library/src/main/java/io/ona/kujaku/utils/LocationSettingsHelper.java [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+
+/**
+ * Created by Ephraim Kigamba - ekigamba@ona.io on 31/10/2018
+ */
+
+public class LocationSettingsHelper {
+
+    private static final String TAG = LocationSettingsHelper.class.getName();
+
+    public static void checkLocationEnabled(Activity activity) {
```
Comment (vincent-karuri) [inline library/src/main/java/io/ona/kujaku/utils/LocationSettingsHelper.java]: Does this check whether Location Services are enabled or does it check that specific Location Services parameters are satisfied?

It's not clear from the name, so maybe some short documentation on the method may be helpful.

Or maybe it could be renamed to `verifyLocationServicesSpecs` as a suggestion?

File: library/src/test/java/io/ona/kujaku/views/KujakuMapViewTest.java [hunk 2]
```diff
@@ -0,0 +1,214 @@
...
+
+        kujakuMapView.showCurrentLocationBtn(true);
+        assertEquals(View.VISIBLE, currentLocationBtn.getVisibility());
+
+        kujakuMapView.showCurrentLocationBtn(false);
+        assertEquals(View.GONE, currentLocationBtn.getVisibility());
+    }
+
+    @Test
+    public void focusOnUserLocationShouldChangeTargetIconWhenGivenCalled() throws NoSuchFieldException, IllegalAccessException {
```
Comment (vincent-karuri) [inline library/src/test/java/io/ona/kujaku/views/KujakuMapViewTest.java]: Does this really test that the target icon is changed?

**Comment by vincent-karuri** [comment]
Please fix the merge conflicts.

File: library/src/test/java/io/ona/kujaku/views/KujakuMapViewTest.java (hunk 2 above)
Comment (ekigamba) [reply library/src/test/java/io/ona/kujaku/views/KujakuMapViewTest.java]: Added the assert for icon change
