### PR TITLE
Update Overriden mapbox layout & fix location client

### LINKED ISSUE #263: Handle null locations on getLastLocation and remove stale last locations
This seems that it can happen on rare occasions
https://developer.android.com/training/location/retrieve-current#java

- [x] Handle null locations after calling `getLastLocation` on the `FusedLocationClient`
- [x] Reset `lastLocation` to null if the `location services` or location on the device has been turned off
- [x] Improve `last location` and `location updates` accuracy and suitability by using the algorithm provided by google https://developer.android.com/guide/topics/location/strategies#BestEstimate
- [x] To be able to save battery, once an accurate location have been retrieved. Can the Geowidget support a way for the host app to reduce the frequency of updates? This will be configurable after the initial default setup of update intervals to support throttling down update requests with an aim to reduce on power consumption

As requested by @githengi

### LINKED ISSUE #268: Update the mapview view xml to use AppCompatImageView as in the library
After the Mapbox upgrade to 6.7.2, the Mapbox SDK uses AppCompatImageView for the images view instead of the basic ImageView. We should also change the overriding layout `mapbox_mapview_internal.xml` to use the same

### PR DESCRIPTION
**Pull request by ekigamba**
Fixes #268
Fixes #263

The `AndroidLocationClient` is renamed to `GoogleLocationClient` since it wraps on capability dependent on the google location services. `AndroidLocationClient` is used to name classes that provide bare location functionality available on devices(ODK Collect & Mapbox SDK follow this), even without the google location services.

### CODE REVIEW

File: library/src/main/java/io/ona/kujaku/location/clients/AndroidLocationClient.java [hunk 1]
```diff
@@ -96,6 +108,63 @@ public void onSuccess(Location location) {
         }
     }
 
+    private void registerForGpsStatusStop() {
```
Comment (vincent-karuri) [inline library/src/main/java/io/ona/kujaku/location/clients/AndroidLocationClient.java]: Could this be clearer like `registerForGpsStopEvent`, and same for unregister?

File: library/src/main/java/io/ona/kujaku/location/clients/AndroidLocationClient.java [hunk 2]
```diff
@@ -96,6 +108,63 @@ public void onSuccess(Location location) {
...
+            Log.e(TAG, Log.getStackTraceString(ex));
+        }
+    }
+
+    private void unregisterForGpsStatusStop() {
+        try {
+            if (Build.VERSION.SDK_INT > 23) {
+                locationManager.unregisterGnssStatusCallback((GnssStatus.Callback) gpsStatusCallback);
+            } else {
+                locationManager.addGpsStatusListener((GpsStatus.Listener) gpsStatusCallback);
```
Comment (vincent-karuri) [inline library/src/main/java/io/ona/kujaku/location/clients/AndroidLocationClient.java]: Why is this add instead of unregister?

File: library/src/main/java/io/ona/kujaku/location/clients/AndroidLocationClient.java [hunk 3]
```diff
@@ -96,6 +108,63 @@ public void onSuccess(Location location) {
         }
     }
 
+    private void registerForGpsStatusStop() {
+        try {
+            if (gpsStatusCallback != null) {
```
Comment (vincent-karuri) [inline library/src/main/java/io/ona/kujaku/location/clients/AndroidLocationClient.java]: Isn't this initially null? Will this block ever run?

File: library/src/main/java/io/ona/kujaku/location/clients/GoogleLocationClient.java [hunk 4]
```diff
@@ -0,0 +1,298 @@
...
+        }
+    }
+
+    private void unregisterForGpsStatusStop() {
+        if (gpsStatusCallback != null) {
+            try {
+                if (Build.VERSION.SDK_INT > 23) {
+                    locationManager.unregisterGnssStatusCallback((GnssStatus.Callback) gpsStatusCallback);
+                } else {
+                    locationManager.addGpsStatusListener((GpsStatus.Listener) gpsStatusCallback);
```
Comment (vincent-karuri) [inline library/src/main/java/io/ona/kujaku/location/clients/GoogleLocationClient.java]: Why is this add instead of unregister?

File: library/src/main/java/io/ona/kujaku/location/clients/GoogleLocationClient.java [hunk 5]
```diff
@@ -0,0 +1,298 @@
...
+                Toast.makeText(context, R.string.location_disabled_location_permissions_not_granted, Toast.LENGTH_LONG)
+                        .show();
+            }
+        } else {
+            setLocationListener(null);
+            Log.e(TAG, "The provider (" + getProvider() + ") is not enabled");
+        }
+    }
+
+    private void registerForGpsStatusStop() {
```
Comment (vincent-karuri) [inline library/src/main/java/io/ona/kujaku/location/clients/GoogleLocationClient.java]: Could this be clearer like `registerForGpsStoppedEvent`, and same for unregister?

File: library/src/main/java/io/ona/kujaku/views/KujakuMapView.java [hunk 6]
```diff
@@ -1211,6 +1213,21 @@ public void onMapReady(MapboxMap mapboxMap) {
         }
     }
 
+    @Override
+    public boolean changeLocationUpdates(long updateInterval, long fastestUpdateInterval, int accuracyLevel) {
+        if (getLocationClient() != null) {
```
Comment (vincent-karuri) [inline library/src/main/java/io/ona/kujaku/views/KujakuMapView.java]: Should there be validation for the arguments in this function?

I think it's possible to give invalid ones e.g. negatives.

File: library/src/main/java/io/ona/kujaku/views/KujakuMapView.java [hunk 7]
```diff
@@ -1211,6 +1213,21 @@ public void onMapReady(MapboxMap mapboxMap) {
         }
     }
 
+    @Override
+    public boolean changeLocationUpdates(long updateInterval, long fastestUpdateInterval, int accuracyLevel) {
```
Comment (vincent-karuri) [inline library/src/main/java/io/ona/kujaku/views/KujakuMapView.java]: Instead of of `changeLocationUpdates`, how does `customizeLocationUpdates` sound?

File: library/src/main/java/io/ona/kujaku/views/KujakuMapView.java [hunk 8]
```diff
@@ -267,6 +268,14 @@ public void onLocationChanged(Location location) {
                 }
             }
         });
+
+        if (locationClientCallbacks.size() > 0) {
```
Comment (vincent-karuri) [inline library/src/main/java/io/ona/kujaku/views/KujakuMapView.java]: Do we need this if statement?

File: library/src/main/java/io/ona/kujaku/location/clients/GoogleLocationClient.java [hunk 9]
```diff
@@ -0,0 +1,298 @@
...
+    public void requestLocationUpdates(@NonNull android.location.LocationListener locationListener
+            , @NonNull LocationRequest locationRequest) {
+        setLocationListener(locationListener);
+        if (isProviderEnabled()) {
+            try {
+                fusedLocationClient.getLastLocation()
+                        .addOnSuccessListener((Activity) context, new OnSuccessListener<Location>() {
+                            @Override
+                            public void onSuccess(Location location) {
+                                if (lastLocation == null || location.getTime() > lastLocation.getTime()) {
```
Comment (vincent-karuri) [inline library/src/main/java/io/ona/kujaku/location/clients/GoogleLocationClient.java]: Why isn't this using the refined location accuracy method `isBetterLocation`?

Comment (vincent-karuri) [reply library/src/main/java/io/ona/kujaku/location/clients/GoogleLocationClient.java]: Could location be null here causing a NPE?

File: library/src/main/java/io/ona/kujaku/views/KujakuMapView.java (hunk 7 above)
Comment (ekigamba) [reply library/src/main/java/io/ona/kujaku/views/KujakuMapView.java]: I personally think that `changeLocationUpdates` still sounds OK and feels more norm to me

File: library/src/main/java/io/ona/kujaku/location/clients/GoogleLocationClient.java (hunk 9 above)
Comment (ekigamba) [reply library/src/main/java/io/ona/kujaku/location/clients/GoogleLocationClient.java]: Cool, fixing this

File: library/src/main/java/io/ona/kujaku/views/KujakuMapView.java (hunk 7 above)
Comment (vincent-karuri) [reply library/src/main/java/io/ona/kujaku/views/KujakuMapView.java]: OK.

File: library/src/main/java/io/ona/kujaku/views/KujakuMapView.java [hunk 10]
```diff
@@ -1217,7 +1215,7 @@ public void onMapReady(MapboxMap mapboxMap) {
 
     @Override
     public boolean changeLocationUpdates(long updateInterval, long fastestUpdateInterval, int accuracyLevel) {
-        if (getLocationClient() != null) {
+        if (updateInterval > -1 && fastestUpdateInterval > -1 && getLocationClient() != null) {
```
Comment (vincent-karuri) [inline library/src/main/java/io/ona/kujaku/views/KujakuMapView.java]: Could you also add a check for accuracyLevel.

I also see it's not used in the function, so it can alternatively be removed?

**Comment by vincent-karuri** [comment]
I think some tests are now failing.

Please fix the build.

File: library/src/main/java/io/ona/kujaku/views/KujakuMapView.java [hunk 11]
```diff
@@ -1215,11 +1215,15 @@ public void onMapReady(MapboxMap mapboxMap) {
 
     @Override
     public boolean changeLocationUpdates(long updateInterval, long fastestUpdateInterval, int accuracyLevel) {
-        if (updateInterval > -1 && fastestUpdateInterval > -1 && getLocationClient() != null) {
+        if (updateInterval > -1 && fastestUpdateInterval > -1 && (accuracyLevel == LocationRequest.PRIORITY_HIGH_ACCURACY
```
Comment (vincent-karuri) [inline library/src/main/java/io/ona/kujaku/views/KujakuMapView.java]: If the user will never have any option other than `LocationRequest.PRIORITY_HIGH_ACCURACY`, then there is no need to have an accuracyLevel argument.

Keeping it as it is would mean that the user will be unable to set the other parameters if they mistakenly set a lower priority. 

Is this desirable?
